---
sidebar: sidebar
permalink: oracle/tiering/whole_datafiles.html
keywords: TR-4695, oracle, storage, tiering, fabricpool
summary: Database Snapshot Tiering with FabricPool
---

= Full Datafile tiering

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Many databases include datafiles organized by date, and such data is generally increasingly less likely to be accessed as it ages. For example, a large billing database might contain five years of customer data, but only the most recent few months are active. FabricPool can be used to relocate older datafiles to the capacity tier.

Some databases, such as an Oracle database using the Information Lifecycle Management assistant, can relocate datafiles between filesystems based on certain criteria. Such a system could be used with FabricPool to relocate files from active data volumes to archival data volumes. For example, the primary datafiles containing the most recent three months of data might reside on SSD storage without FabricPool. After 90 days, the individual datafiles are then moved to a volume configured with a two-day cooling period to drive rapid tiering to the capacity layer.

The datafiles could also share a common FabricPool-enabled volume with a longer cooling period to make sure that required data remains available on the performance tier. There is some risk that data is relocated to the capacity tier earlier than desired, but the cooling period only applies after data is not accessed for the required period. Data does not immediately become tiered merely because the cooling period has elapsed.

[NOTE]
Any type of access to data resets the heat map data. Therefore, database full table scans and even backup activity that reads the source files prevents tiering because the required `tiering-minimum-cooling-days` threshhold is never reached.

== Policies

The `tiering-minimum-cooling-days` policy should be set high enough so that files that you might need remain on the performance tier. For example, a database for which the most recent 60 days of data is required with the optimal performance warrants setting the `tiering-minimum-cooling-days` period to 60. Similar results can also be achieved based on the file access patterns. For example, if the most recent 90 days of data is required and the application is accessing that 90- day span of data, then the data would remain on the performance tier. By setting the `tiering-minimum-cooling-days` period to 2, you get prompt tiering after the data becomes less active.

The `auto` policy is required to drive tiering of datafiles because only the `auto` policy affects blocks that are in the active filesystem.

[NOTE]
Any type of access to data resets the heat map data. Therefore, database full table scans and even backup activity that reads the source files prevents tiering because the required `tiering-minimum-cooling-days` threshhold is never reached.
