---
sidebar: sidebar
permalink: common/ontap/svm.html
keywords: svm
summary: SVM provisioning
---
= Storage Virtual Machines
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
A storage virtual machine (SVM), known as a vserver at the ONTAP CLI, is a basic functional unit of storage, and it is useful to compare an SVM to a guest on a VMware ESX server.

When first installed, ESX has no preconfigured capabilities, such as hosting a guest OS or supporting an end-user application. It is an empty container until a virtual machine (VM) is defined. ONTAP is similar. When ONTAP is first installed, it has no data-serving capabilities until an SVM is created. It is the SVM personality that defines the data services.

As with other aspects of storage architecture, the best options for SVM and logical interface (LIF) design depend heavily on scaling requirements and business needs.

== SVMs
There is no official best practice for provisioning SVMs for ONTAP. The right approach depends on management and security requirements.

Most customers operate one primary SVM for most of their day-to-day requirements but then create a small number of SVMs for special needs. For example, you might wish to create:

* An SVM for a critical business database managed by a specialist team
* An SVM for a development group to whom complete administrative control has been given so that they can manage their own storage independently
* An SVM for sensitive business data, such as human resources or financial reporting data, for which the administrative team must be limited

In a multitenant environment, each tenant's data can be given a dedicated SVM. The limit for the number of SVMs and LIFs per cluster, HA pair, and node are dependant on the protocol being used, the node model, and the version of ONTAP.  Consult the link:https://hwu.netapp.com/[NetApp Hardware Universe] for these limits.
