---
sidebar: sidebar
permalink: common/metrocluster/overview.html
keywords: metrocluster, syncmirror
summary: MetroCluster and the role of syncmirror
---

= SyncMirror
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
MetroCluster refers to ONTAP synchronously mirrored storage and numerous additional features that deliver a comprehensive, easily managed RPO=0 solution. 

In addition, integrated solutions such as MetroCluster simplify today's complicated, scale-out databases, application, and virtualization infrastructures. MetroCluster replaces multiple, external data protection products and strategies with one simple, central storage array. It provides integrated backup, recovery, disaster recovery, and high availability (HA) within a single clustered storage system.

NetApp offers two high-availability synchronous mirroring technologies - SnapMirror Business Continuity (SM-BC) and MetroCluster. The primary difference is granularity.

If you only need select workloads to be synchronous replicated, SM-BC is the better option. If you need to replicate entire environments or even data centers, MetroCluster is a better option. In addition, SM-BC is currently SAN-only while MetroCluster is multiprotocol, including SAN, NFS, and SMB.