---
sidebar: sidebar
permalink: oracle/host-configuration/windows.html
keywords: TR-3633, oracle, database, ontap, windows
summary: Oracle on ONTAP using Microsoft Windows
---

= Microsoft Windows
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-08-12 10:15:58.810042
//

[.lead]
This section addresses configuration topics specific to the Microsoft Windows OS.

== NFS

Oracle supports the use of Microsoft Windows with the direct NFS client. This capability offers a path to the management benefits of NFS, including the ability to view files across environments, dynamically resize volumes, and leverage a less expensive IP protocol. See the official Oracle documentation for information on installing and configuring a database on Microsoft Windows using DNFS. No special best practices exist.

== SAN

For optimum compression efficiency, make sure that NTFS file systems use an 8192 byte or larger allocation unit. Use of a 4096-byte allocation unit, which is generally the default, damages efficiency.
