---
sidebar: sidebar
permalink: oracle/virtualization/intro.html
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM
summary: Introduction to database virtualization
---
= Virtualization

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Virtualization of databases with VMware ESX, Oracle OVM, or KVM is an increasingly common choice for NetApp customers who chose virtualization for even their most mission-critical databases.

Many misconceptions exist on the support policies for virtualization, particularly for VMware products. Indeed, it is not uncommon to hear that Oracle does not support virtualization in any way. This notion is incorrect and leads to missed opportunities for virtualization. Oracle Doc ID 249212.1 discusses known issues in an Oracle environment and also specifies support for RAC.

A customer with a problem unknown to Oracle might be asked to reproduce the problem on physical hardware. An Oracle customer running a bleeding-edge version of a product might not want to use virtualization because of the potential for new bug discovery. However, this situation has not been a problem in practice for virtualization customers using generally available product versions.

== Storage presentation
Customers considering virtualization of their databases should base their storage decisions on their business needs. Although this is a generally true statement for all IT decisions, it is especially important for virtualization, because the size and scope of projects vary considerably.

There are four basic options for storage presentation:

* iSCSI LUNs managed by the iSCSI initiator on the VM, not the hypervisor
* NFS file systems mounted by the VM, not a virtual machine disk (VMDK)
* Hypervisor datastores

As a general rule, avoid using datastores for Oracle files. There are many reasons for this recommendation:

* *Transparency.* When a VM owns its file systems, it is easier for a database administrator or a system administrator to identify the source of the file systems for their data.
* *Performance.* Testing has shown that there is a performance effect from channeling all I/O through a hypervisor datastore.
* *Manageability.* When a VM owns its file systems, the use or nonuse of a hypervisor layer affects manageability. The same procedures for provisioning, monitoring, data protection, and so on can be used across the entire estate, including both virtualized and nonvirtualized environments.
* *Stability and troubleshooting.* When a VM owns its file systems, delivering good, stable performance and troubleshooting problems are much simpler because the entire storage stack is present on the VM. The hypervisor's only role is to transport FC or IP frames. When a datastore is included in a configuration, it complicates the configuration by introducing another set of timeouts, parameters, log files, and potential bugs.
* *Portability.* When a VM owns its file systems, the process of moving an Oracle environment becomes much simpler. File systems can easily be moved between virtualized and nonvirtualized guests.
* *Vendor lock-in.* After data is placed in a datastore, using a different hypervisor or taking the data out of the virtualized environment entirely becomes very difficult.
* *Snapshot enablement.* In some cases, backups in a virtualized environment can become a problem because of the relatively limited bandwidth. For example, a four-port 10GbE trunk might be sufficient to support the day-to-day performance needs of many virtualized databases. However, such a trunk would be insufficient to perform backups using RMAN or other backup products that require streaming a full-sized copy of the data.
+
Using VM-owned file systems makes it easier to leverage Snapshot-based backups and restores. A VM-owned file system offloads the work of performing backups onto the storage system. There is no need to overbuild the hypervisor configuration purely to support the bandwidth and CPU requirements in the backup window.

[TIP]
*NetApp recommends* avoiding placing Oracle data on a datastore to achieve optimum performance and manageability,. Use guest-owned file systems such as NFS or iSCSI file systems managed by the guest or with RDMs.

== Paravirtualized drivers
For optimum performance, the use of paravirtualized network drivers is critical. When a datastore is used, a paravirtualized SCSI driver is required. A paravirtualized device driver allows a guest to integrate more deeply into the hypervisor, as opposed to an emulated driver in which the hypervisor spends more CPU time mimicking the behavior of physical hardware.

The performance of most databases is limited by storage. Therefore, the extra latency introduced by a network or SCSI driver is particularly noticeable. NetApp Customer Support has encountered many performance complaints that were resolved by installing paravirtualized drivers. During one customer proof of concept, databases showed better performance under ESX than with the same hardware running as bare metal. The tests were very I/O intensive, and the performance difference was attributed to the use of the ESX paravirtualized network drivers.

[TIP]
*NetApp recommends* always using paravirtualized network drivers and SCSI drivers.

== Overcommitting RAM
Overcommitting RAM means configuring more virtualized RAM on various hosts than exists on the physical hardware. Doing so can cause unexpected performance problems. When virtualizing a database, the underlying blocks of the Oracle SGA must not be swapped out to storage by the hypervisor. Doing so causes highly unstable performance results.

[TIP]
*NetApp recommends* to not configure a hypervisor in a way that allows Oracle SGA blocks to be swapped out.
