---
sidebar: sidebar
permalink: oracle/oracle-dp-consistency-group-backup.html
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles
summary: Consistency group backups for Oracle databases on ONTAP
---
= Oracle database consistency group backups

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
For the simplest possible backup, just place the entire Oracle database in a single ONTAP volume

Protecting the datafiles, archive logs, redo logs, and controlfiles with a single snapshot is a valid backup, restore, and replication method.  However, the RPO is limited to the point of the backup itself. It is suitable for an RPO of one hour or greater. If a database spans volumes, cg-snapshots are required using one of the tools discussed previously.

As an example, the entire database can be in a single volume with the following snapshot schedule:

* 72 hourly snapshots
* 30 nightly snapshots
* 12 monthly snapshots

This delivers an RPO of one hour over the rolling period of the preceding 72 hours, plus additional nightly and monthly backups. Multiple databases or application files can also be included in the single volume or set of cg-snapshots to deliver consistent backups across a larger environment.
