---
sidebar: sidebar
permalink: oracle/oracle-host-config-windows.html
keywords: oracle, database, ontap, windows
summary: Oracle databases with Microsoft Windows
---
= Oracle databases with Microsoft Windows

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Configuration topics for Oracle database on Microsoft Windows with ONTAP..

== NFS
Oracle supports the use of Microsoft Windows with the direct NFS client. This capability offers a path to the management benefits of NFS, including the ability to view files across environments, dynamically resize volumes, and leverage a less expensive IP protocol. See the official Oracle documentation for information on installing and configuring a database on Microsoft Windows using DNFS. No special best practices exist.

== SAN
For optimal compression efficiency, ensure the NTFS file system uses an 8K or larger allocation unit. Use of a 4K allocation unit, which is generally the default, negatively impacts compression efficiency.