---
sidebar: sidebar
permalink: mssql/benchmarking.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---


[.lead]

Placeholder



= Benchmarking

The Transaction Process Council (TPC) is a nonprofit corporation founded to define transaction processing and database benchmarks and to disseminate objective, verifiable TPC performance data to the industry. TPC tests simulate complete compute environments in which a population of users executes transactions against databases. Table 1 summarizes the typical SQL Server testing workloads.

Table 1) Typical SQL Server workloads.

Workload type
TPC test
Read/write ratio (percentages)
OLTP
TPC-C
~75/25

TPC-E
~90/10
DSS
TPC-H
~100/0
Although various workload generation options are available, we generally focus our efforts on measuring the performance of SQL Server databases when handling transactional workloads, and we use the TPC-E tools from Microsoft or TPC-H using HammerDB (HammerDB.com). The detailed instructions on how to use these specific benchmarks are beyond the scope of this document.
