---
sidebar: sidebar
permalink: mssql/data-protection.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---

= SQL Server data protection with ONTAP

[.lead]
Protecting database is critical to any organization. As data size and count of databases have increased, maintaining recovery time objective (RTO) and recovery point objective (RPO) is very crucial.

The main consideration for database backup is leveraging NetApp Snapshot technology. Data protection planning on ONTAP is discussed link:../common/dp/overview.html[here]. Application consistent backup and database layout are other key consideration to achieve RTO and RPO which can be orchestrated by NetApp SnapCenter.

== SnapCenter

SnapCenter is the NetApp data protection software for enterprise applications.SQL Server databases can be quickly and easily protected using NetApp SnapCenter software with the Plug-in for SQL Server and the Plug-in for Microsoft Windows.

This products enable application-consistent backup, automated cloning, and restore and recovery of SQL Server databases, instances, or availability groups. NetApp recommends using SnapCenter to create Snapshot copies. For more details about the SQL Server Plug-in for SnapCenter, see link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf[TR-4714: Best Practice Guide for SQL Server Using NetApp SnapCenter.]

== NetApp SnapMirror

NetApp SnapMirror technology offers a fast and flexible enterprise solution for mirroring or replicating data over LANs and WANs. SnapMirror technology transfers only modified 4KB data blocks to the destination after the initial base transfer, significantly reducing network bandwidth requirements. SnapMirror provides asynchronous volume-level replication that is based on a configured replication update interval. 
The following are recommendations for SnapMirror for SQL Server:

• If CIFS is used, the destination SVM must be a member of the same Active Directory domain of which the source
SVM is a member so that the access control lists (ACLs) stored within NAS files are not broken
during recovery from a disaster.
• Using destination volume names that are the same as the source volume names is not required but
can make the process of mounting destination volumes into the destination simpler to manage. If
CIFS is used, you must make the destination NAS namespace identical in paths and directory
structure to the source namespace.
• For consistency purposes, do not schedule SnapMirror update from the controllers. However, enable
SnapMirror update from SnapCenter to update SnapMirror after either full or log backup is completed.
• Distribute volumes that contain SQL Server data across different nodes in the cluster to allow all
cluster nodes to share SnapMirror replication activity. This distribution optimizes the use of node
resources.

For more information about SnapMirror, see link:https://www.netapp.com/us/media/tr-4015.pdf[TR-4015: SnapMirror Configuration and Best Practices Guide for ONTAP 9].

NetApp and partner professional services experts are available for assistance in complex projects. Even if assistance is not required during the project, NetApp strongly encourages new customers to use professional services for assistance in developing a high-level approach. 