---
sidebar: sidebar
permalink: mssql/host-log.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---

= Host log directory

[.lead]
SQL Server uses a host log directory to store transaction log backup data. This is at the host level. 

Each SQL Server host used by SnapCenter must have a host log directory configured to perform log backups. SnapCenter has a database repository, so metadata related to backup, restore, or cloning operations is stored in a central database repository.

The sizes of the host log directory is calculated as follows:

Size of host log directory = ( (maximum DB LDF size × daily log change rate %) × (snapshot retention) ÷ (1 – LUN overhead space %)

The host log directory sizing formula assumes a 10% LUN overhead space

Place the host log directory on a dedicated volume or LUN. The amount of data in the host log directory depends on the size of the backups and the number of days that backups are retained. SnapCenter allows only one host log directory per SQL Server host. You can configure the host log directories at SnapCenter --> Host --> Configure Plug-in.

The following are NetApp recommendations for a host log directory:

* Make sure that the host log directory is not shared by any other type of data that can potentially corrupt the backup Snapshot copies.

* Do not place user databases or system databases on a LUN that hosts mount points.

* Use SnapCenter wizards to migrate databases to NetApp storage so that the databases are stored in valid locations, enabling successful SnapCenter backup and restore operations. Keep in mind that the migration process is disruptive and can cause the databases to go offline while the migration is in progress.

* The following conditions must be in place for failover cluster instances (FCIs) of SQL Server:

* If you are using a failover cluster instance, the host log directory LUN must be a cluster disk resource in the same cluster group as the SQL Server instance being backed up SnapCenter.

* If you are using a failover cluster instance, user databases must be placed on shared LUNs that are physical disk cluster resources assigned to the cluster group associated with the SQL Server instance.

The following are NetApp recommendations for databases on LUNs:

* Make sure that the user database and the host log directory are on separate volumes to prevent the retention policy from overwriting Snapshot copies when these are used with SnapVault technology.

* Make sure that SQL Server databases reside on LUNs separate from LUNs that have nondatabase files, such as full-text search-related files.

* Placing database secondary files (as part of a filegroup) on separate volumes improves the performance of the SQL Server database. This separation is valid only if the database’s .mdf file does not share its LUN with any other .mdf files.

* Create LUNs with SnapCenter Plug-in for Microsoft Windows whenever possible. If you want to create LUNs with DiskManager or other tools, make sure that the allocation unit size is set to 64K for partitions when formatting the LUNs.
