---
sidebar: sidebar
permalink: mssql/max-worker-threads.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---


[.lead]

Placeholder



= Max worker threads

The max worker threads option helps to optimize performance when large numbers of clients are connected to SQL Server. Normally, a separate operating system thread is created for each query request. If hundreds of simultaneous connections are made to SQL Server, then one thread per query request consumes large amounts of system resources. The max worker threads option helps improve performance by enabling SQL Server to create a pool of worker threads to service a larger number of query requests.

The default value is 0, which allows SQL Server to automatically configure the number of worker threads at startup. This works for most systems. Max worker threads is an advanced option and should not be altered without assistance from an experienced database administrator (DBA).

When should you configure SQL Server to use more worker threads? If the average work queue length for each scheduler is above 1, you might benefit from adding more threads to the system, but only if the load is not CPU-bound or experiencing any other heavy waits. If either of those is happening, adding more threads does not help because they end up waiting for other system bottlenecks. For more information about max worker threads, see Configure the max worker threads Server Configuration Option. Figure 3 indicates how to adjust maximum worker threads.

Figure 3) Configuring max worker threads using SQL Server Management Studio.



The following example shows how to configure the max work threads option using T-SQL.

EXEC sp_configure 'show advanced options', 1;  

GO  

RECONFIGURE ;  

GO  

EXEC sp_configure 'max worker threads', 900 ;  

GO  

RECONFIGURE;  

GO  
