---
sidebar: sidebar
permalink: mssql/max-server-memory.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---

= Max server memory

[.lead]
The max server memory option sets the maximum amount of memory that the SQL Server instance can use.

It is generally used if multiple applications are running on the same server where SQL Server is running and you want to guarantee that these applications have sufficient memory to function properly.

Some applications only use whatever memory is available when they start and do not request more even if needed. That is where the max server memory setting comes into play.

On a SQL Server cluster with several SQL Server instances, each instance could be competing for resources. Setting a memory limit for each SQL Server instance can help guarantee best performance for each instance.

NetApp recommends leaving at least 4GB to 6GB of RAM for the operating system to avoid performance issues. Figure 2 displays how to set up minimum and maximum server memory.

Figure 2) Adjusting minimum and maximum server memory using SQL Server Management Studio.

Using SQL Server Management Studio to adjust minimum or maximum server memory requires a restart of the SQL Server service. You can adjust server memory using transact SQL (T-SQL) using this code:

EXECUTE sp_configure 'show advanced options', 1

GO

EXECUTE sp_configure 'min server memory (MB)', 2048

GO

EXEC sp_configure 'max server memory (MB)', 120832

GO

RECONFIGURE WITH OVERRIDE
