---
sidebar: sidebar
permalink: mssql/storage-design.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---

= Storage considerations

[.lead]
The combination of NetApp storage solutions and Microsoft SQL Server enables the creation of enterprise-level database storage designs that can meet today’s most demanding application requirements. To optimize both technologies, it is vital to understand the SQL Server I/O pattern and characteristics. A well-designed storage layout for a SQL Server database supports the performance of SQL Server and the management of the SQL Server infrastructure. A good storage layout also allows the initial deployment to be successful and the environment to grow smoothly over time as the business grows.

== Data storage design

For SQL Server databases that do not use SnapCenter to perform backups, Microsoft recommends placing the data and log files on separate drives. For applications that simultaneously update and request data, the log file is write intensive, and the data file (depending on your application) is read/write intensive. For data retrieval, the log file is not needed. Therefore, requests for data can be satisfied from the data file placed on its own drive.

When you create a new database, Microsoft recommends specifying separate drives for the data and logs. To move files after the database is created, the database must be taken offline. For more Microsoft recommendations, see Place Data and Log Files on Separate Drives.

== Aggregates

Aggregates are the primary storage containers for NetApp storage configurations and contain one or
more RAID groups consisting of both data disks and parity disks.
NetApp has performed various I/O workload characterization tests using shared and dedicated
aggregates with data files and transaction log files separated. The tests show that one large aggregate
with more RAID groups and spindles optimizes and improves storage performance and is easier for
administrators to manage for two reasons:

• One large aggregate makes the I/O capabilities of all spindles available to all files.
• One large aggregate enables the most efficient use of disk space.

For high availability (HA), place the SQL Server Always On Availability Group secondary synchronous
replica on a separate storage virtual machine (SVM) in the aggregate. For disaster recovery purposes,
place the asynchronous replica on an aggregate that is part of a separate storage cluster in the DR site,
with content replicated by using NetApp SnapMirror® technology.
NetApp recommends having at least 10% free space available in an aggregate for optimal storage
performance.

== Volumes

NetApp FlexVol volumes are created and reside inside aggregates. Many volumes can be created in a
single aggregate, and each volume can be expanded, shrunk, or moved between aggregates with no
user downtime.

=== Volume design considerations

Before you create a database volume design, it is important to understand how the SQL Server I/O
pattern and characteristics vary depending on the workload and on the backup and recovery
requirements. See the following NetApp recommendations for flexible volumes:

• Use flexible volumes to store SQL Server database files and avoid sharing volumes between hosts.
• Use NTFS mount points instead of drive letters to surpass the 26-drive-letter limitation in Windows. When using volume mount points, it is a general recommendation to give the volume label the same name as the mount point.
• When appropriate, configure a volume autosize policy to help prevent out-of-space conditions. 17 Best practice guide for Microsoft SQL Server with ONTAP © 2022 NetApp, Inc. All rights reserved. 
• Enable read reallocation on the volume when the SQL Server database I/O profile consists of mostly large sequential reads, such as with decision support system workloads. Read reallocation optimizes the blocks to provide better performance.
• If you install SQL Server on an SMB share, make sure that Unicode is enabled on the SMB/CIFS volumes for creating folders.
• Set the NetApp snapshot copy reserve value in the volume to zero for ease of monitoring from an operational perspective.
• Disable storage Snapshot™ copy schedules and retention policies. Instead, use SnapCenter to coordinate Snapshot copies of the SQL Server data volumes.
• Place the SQL Server system databases on a dedicated volume or VMDK.
• tempdb is a system database used by SQL Server as a temporary workspace, especially for I/Ointensive DBCC CHECKDB operations. Therefore, place this database on a dedicated volume with a separate set of spindles. In large environments in which volume count is a challenge, you can consolidate tempdb into fewer volumes and store it in the same volume as other system databases after careful planning. Data protection for tempdb is not a high priority because this database is recreated every time SQL Server is restarted.
• Place user data files (.mdf) on separate volumes because they are random read/write workloads. It is common to create transaction log backups more frequently than database backups. For this reason, place transaction log files (.ldf) on a separate volume or VMDK from the data files so that independent backup schedules can be created for each. This separation also isolates the sequential write I/O of the log files from the random read/write I/O of data files and significantly improves SQL Server performance.
• Create the host log directory on the dedicated FlexVol volume to which SnapCenter copies transaction logs.

== LUN

* Make sure that the user database files and the log directory to store log backup are on separate volumes to prevent the retention policy from overwriting snapshots when these are used with SnapVault technology.
* Make sure that SQL Server databases reside on LUNs separate from LUNs that have nondatabase files, such as full-text search-related files.
* Placing database secondary files (as part of a filegroup) on separate volumes improves the performance of the SQL Server database. This separation is valid only if the database’s .mdf file does not share its LUN with any other .mdf files.
* If you create LUNs with DiskManager or other tools, make sure that the allocation unit size is set to 64K for partitions when formatting the LUNs.

== Log directory

Log directory is specified in SQL Server to store transaction log backup data at the host level. If you are using SnapCenter to backup log files then each SQL Server host used by SnapCenter must have a host log directory configured to perform log backups. SnapCenter has a database repository, so metadata related to backup, restore, or cloning operations is stored in a central database repository.

The sizes of the host log directory is calculated as follows:
Size of host log directory = ( (maximum DB LDF size × daily log change rate %) × (snapshot retention) ÷ (1 – LUN overhead space %)
The host log directory sizing formula assumes a 10% LUN overhead space

Place the log directory on a dedicated volume or LUN. The amount of data in the host log directory depends on the size of the backups and the number of days that backups are retained. SnapCenter allows only one host log directory per SQL Server host. You can configure the host log directories at SnapCenter --> Host --> Configure Plug-in.

The following are NetApp recommendations for a host log directory:

* Make sure that the host log directory is not shared by any other type of data that can potentially corrupt the backup snapshot data.
* Do not place user databases or system databases on a LUN that hosts mount points.
*  Use SnapCenter wizards to migrate databases to NetApp storage so that the databases are stored in valid locations, enabling successful SnapCenter backup and restore operations. Keep in mind that the migration process is disruptive and can cause the databases to go offline while the migration is in progress.
* The following conditions must be in place for failover cluster instances (FCIs) of SQL Server:
    - If you are using a failover cluster instance, the host log directory LUN must be a cluster disk resource in the same cluster group as the SQL Server instance being backed up SnapCenter.
    - If you are using a failover cluster instance, user databases must be placed on shared LUNs that are physical disk cluster resources assigned to the cluster group associated with the SQL Server instance.