---
sidebar: sidebar
permalink: mssql/volumes.html
keywords: MS-SQL,mssql,SQL Server
summary: Microsoft SQL Server on ONTAP
---


[.lead]

Placeholder



= Volumes

NetApp FlexVol volumes are created and reside inside aggregates. Many volumes can be created in a single aggregate, and each volume can be expanded, shrunk, or moved between aggregates with no user downtime.

Before you create a database volume design, it is important to understand how the SQL Server I/O pattern and characteristics vary depending on the workload and on the backup and recovery requirements. See the following NetApp recommendations for flexible volumes:

* Use flexible volumes to store SQL Server database files and avoid sharing volumes between hosts.
* Use NTFS mount points instead of drive letters to surpass the 26-drive-letter limitation in Windows. When using volume mount points, it is a general recommendation to give the volume label the same name as the mount point.
* When appropriate, configure a volume autosize policy to help prevent out-of-space conditions.
* Enable read reallocation on the volume when the SQL Server database I/O profile consists of mostly large sequential reads, such as with decision support system workloads. Read reallocation optimizes the blocks to provide better performance.
* If you install SQL Server on an SMB share, make sure that Unicode is enabled on the SMB/CIFS volumes for creating folders.
* Set the NetApp snapshot reserve value in the volume to zero for ease of monitoring from an operational perspective.
* Disable storage Snapshot™ copy schedules and retention policies. Instead, use SnapCenter to coordinate snapshots of the SQL Server data volumes.
* Place the SQL Server system databases on a dedicated volume or VMDK.
* tempdb is a system database used by SQL Server as a temporary workspace, especially for I/O-intensive DBCC CHECKDB operations. Therefore, place this database on a dedicated volume with a separate set of spindles. In large environments in which volume count is a challenge, you can consolidate tempdb into fewer volumes and store it in the same volume as other system databases after careful planning. Data protection for tempdb is not a high priority because this database is recreated every time SQL Server is restarted.
* Place user data files (.mdf) on separate volumes because they are random read/write workloads. It is common to create transaction log backups more frequently than database backups. For this reason, place transaction log files (.ldf) on a separate volume or VMDK from the data files so that independent backup schedules can be created for each. This separation also isolates the sequential write I/O of the log files from the random read/write I/O of data files and significantly improves SQL Server performance.
* Create the host log directory on the dedicated FlexVol volume to which SnapCenter copies transaction logs.
