---
sidebar: sidebar
permalink: vmware/vmware-vsphere-datastores-fg.html
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols
summary: This page describes the best practices for implementing a NetApp ONTAP storage solution in a VMware vSphere environment.
---

= FlexGroup volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP 9.8 adds support for FlexGroup volume datastores in vSphere, along with support with ONTAP tools for VMware vSphere and SnapCenter plugin for VMware vSphere. FlexGroup simplifies the creation of large datastores and automatically creates a number of constituent volumes to get maximum performance from an ONTAP system. Use FlexGroup with vSphere if you require a single, scalable vSphere datastore with the power of a full ONTAP cluster, or if you have very large cloning workloads that can benefit from the new FlexGroup cloning mechanism.

In addition to extensive system testing with vSphere workloads, ONTAP 9.8 also adds a new copy offload mechanism for FlexGroup datastores. This uses an updated copy engine that uses the first few clones to populate a local cache in each constituent volume. This local cache is then used to rapidly instantiate VM clones on demand.

Consider the following scenario:

* You've created a new FlexGroup with 8 constituents
* The cache timeout for the new FlexGroup is set to 160 minutes

In this scenario, the first 8 clones to complete will be full copies, not local file clones. Any additional cloning of that VM before the 160-second timeout expires will use the file clone engine inside of each constituent in a round-robin fashion to create nearly immediate copies evenly distributed across the constituent volumes.

Every new clone job a volume receives resets the timeout. If a constituent volume in the example FlexGroup does not receive a clone request before the timeout, the cache for that particular VM will be cleared and the volume will need to be populated again. Also, if the source of the original clone changes (e.g., you've updated the template) then the local cache on each constituent will be invalidated to prevent any conflict. The cache is tunable and can be set to match the needs of your environment.

In environments where you are not able to take full advantage of the FlexGroup cache, but still require rapid cross-volume cloning, consider using vVols. Cross-volume cloning with vVols is much faster than using traditional datastores, and does not rely on a cache.

For more information on using FlexGroups with VAAI, refer to this KB article: https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F[VAAI: How does caching work with FlexGroup volumes?^]

ONTAP 9.8 also adds new file-based performance metrics (IOPS, throughput, and latency) for FlexGroup volume files, and these metrics can be viewed in the ONTAP tools for VMware vSphere dashboard and VM reports. The ONTAP tools for VMware vSphere plug-in also allows you to set Quality of Service (QoS) rules using a combination of maximum and/or minimum IOPS. These can be set across all VMs in a datastore or individually for specific VMs.

Here are some additional best practices that NetApp has developed:

* Use FlexGroup volume provisioning defaults. While ONTAP tools for VMware vSphere is recommended because it creates and mounts the FlexGroup within vSphere, ONTAP System Manager or the command line might be used for special needs. Even then, use the defaults such as the number of constituent members per node because this is what has been most thoroughly tested with vSphere. That being said, non-default settings such as changing the number or placement of constituents is still full supported.
* When sizing a FlexGroup based datastore, keep in mind that the FlexGroup consists of multiple smaller FlexVol volumes that create a larger namespace. As such, when using a FlexGroup with eight constituents, be sure and size the datastore to be at least 8x the size of your largest virtual machine. For example, if you have a 6TB VM in your environment, size the FlexGroup datastore no smaller than 48TB.
* Allow FlexGroup to manage datastore space. Autosize and Elastic Sizing have been tested with vSphere datastores. Should the datastore get close to full capacity, use ONTAP tools for VMware vSphere or another tool to resize the FlexGroup volume. FlexGroup keeps capacity and inodes balanced across constituents, prioritizing files within a folder (VM) to the same constituent if capacity allows.
* VMware and NetApp currently support NFSv4.1 session trunking beginning with ONTAP 9.14.1. Refer to the NetApp NFS 4.1 interoperability matrix notes for specific version details. NFSv3 does not support multiple physical paths to a volume but does support nconnect beginning in vSphere 8.0U2. More information on nconnect can be found link:vmware-vsphere-network.html#nfs[here]. For FlexGroup with ONTAP 9.8, our recommended best practice is to let ONTAP tools for VMware vSphere create the FlexGroup, but then you should unmount it, and remount it using round robin DNS in order to distribute the load across the cluster. ONTAP tools only uses one LIF when mounting datastores. After remounting the datastore, ONTAP tools can be used to monitor and manage it.
* FlexGroup vSphere datastore support has been tested up to 1500 VMs with the 9.8 release.
* Use the NFS Plug-In for VMware VAAI for copy offload. Note that while cloning is enhanced within a FlexGroup datastore, as mentioned previously, ONTAP does not provide significant performance advantages versus ESXi host copy when copying VMs between FlexVol and/or FlexGroup volumes. Therefore consider your cloning workloads when deciding to use VAAI or FlexGroups. Modifying the number of constituent volumes is one way to optimize for FlexGroup based cloning. As is tuning the cache timeout.
* Use ONTAP tools for VMware vSphere 9.8 to monitor performance of FlexGroup VMs using ONTAP metrics (dashboard and VM reports), and to manage QoS on individual VMs. These metrics are not currently available through ONTAP commands or APIs.
* QoS (max/min IOPS) can be set on individual VMs or on all VMs in a datastore at that time. Setting QoS on all VMs replaces any separate per-VM settings. Settings do not extend to new or migrated VMs in the future; either set QoS on the new VMs or re-apply QoS to all VMs in the datastore. Nor do FlexGroup QoS policies follow the VM if it is migrated to another datastore. This is in contrast with vVols which can maintain their QoS policy settings if they migrate to another datastore.
* SnapCenter Plug-In for VMware vSphere release 4.4 and later supports backup and recovery of VMs in a FlexGroup datastore on the primary storage system. SCV 4.6 adds SnapMirror support for FlexGroup based datastores.
