---
sidebar: sidebar
permalink: common/dp/snaprestore.html
keywords: ontap, snaprestore
summary: SnapRestore
---

= SnapRestore
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]

Rapid data restoration in ONTAP from a snapshot is delivered by NetApp SnapRestore technology. 

The key values are as follows:

* Individual files or LUNs can be restored in seconds, whether it is a 2TB LUN or a 4KB file.
* An entire container (a NetApp FlexVol volume) of LUNs and/or files can be restored in seconds, whether it is 10GB or 100TB of data.

When a critical dataset is unavailable, critical business operations are down. Tapes can break, and even restores from disk-based backups can be slow to transfer across the network. SnapRestore avoids these problems by delivering near instantaneous restoration of datasets. Even petabyte-scale databases can be completely restored with just a few minutes of effort.

The reason SnapRestore works so quickly and efficiently is due to the nature of a Snapshot copy, which is essentially a parallel read-only view of the contents of a volume at a specific point in time. The active blocks are the real blocks that can be changed, while the Snapshot copy is a read-only view into the state of the blocks that constitute the files and LUNs at the time the Snapshot copy was created.

ONTAP only permits read-only access to snapshot data, but the data can be reactivated with SnapRestore. The Snapshot copy is reenabled as a read-write view of the data, returning the data to its prior state. SnapRestore can operate at the volume or the file level. The technology is essentially the same with a few minor differences in behavior.

== Volume SnapRestore

Volume-based SnapRestore returns the entire volume of data to an earlier state. This operation does not require data movement, meaning that the restore process is essentially instantaneous, although the API or CLI operation might take a few seconds to be processed. Restoring 1GB of data is no more complicated or time-consuming than restoring 1PB of data. This capability is the primary reason many enterprise customers migrate to ONTAP storage systems. It delivers an RTO measured in seconds for even the largest datasets.

One drawback to volume-based SnapRestore is caused by the fact that changes within a volume are cumulative over time. Therefore, each Snapshot copy and the active file data are dependent on the changes leading up to that point. Reverting a volume to an earlier state means discarding all the subsequent changes that had been made to the data. What is less obvious, however, is that this includes subsequently created Snapshot copies. This is not always desirable.

For example, a data retention SLA might specify 30 days of nightly backups. Restoring a dataaset to a snapshot created five days ago with volume SnapRestore would discard all the Snapshot copies created on the previous five days, violating the SLA.

There are a number of options available to address this limitation:

. Data can be copied from a prior Snapshot copy, as opposed to performing a SnapRestore of the entire volume. This method works best with smaller datasets.
. A Snapshot copy can be cloned rather than restored. The limitation to this approach is that the source Snapshot copy is a dependency of the clone. Therefore, it cannot be deleted unless the clone is also deleted or is split into an independent volume.
. Use of file-based SnapRestore.

== File SnapRestore

File-based SnapRestore is a more granular snapshot-based restoration process. Rather than reverting the state of an entire volume, the state of an individual file or LUN is reverted. No Snapshot copies need to be deleted, nor does this operation create any dependency on a prior Snapshot copy. The file or LUN becomes immediately available in the active volume.

No data movement is required during a SnapRestore restore of a file or LUN. However, some internal metadata updates are required to reflect the fact that the underlying blocks in a file or LUN now exist in both a Snapshot copy and the active volume. There should be no effect on performance, but this process blocks the creation of Snapshot copies until it is complete. The processing rate is approximately 5GBps (18TB/hour) based on the total size of the files restored.
