---
sidebar: sidebar
permalink: mysql/intro.html
keywords: MySQL,MariaDB,Percona,database
summary: MySQL on ONTAP
---

= Introduction

MySQL and its variants, including MariaDB and Percona, are widely used for many enterprise applications. These applications range from global social networking sites and massive e-commerce systems to SMB hosting systems containing thousands of database instances. This document describes the configuration requirements and provides guidance on tuning and storage configuration for deploying MySQL on NetApp® ONTAP® data management software

== NetApp ONTAP

For maximum performance and control of data, NetApp ONTAP remains the leading solution. It is the standard storage solution that thousands of customers have relied on for more than 25 years. ONTAP delivers solutions for any environment, ranging from mission-critical database deployments to instant restore scenarios.

ONTAP software is the foundation for advanced data protection and management. However, ONTAP is only the software portion of the solution. There are several hardware environments to choose from:

* ONTAP on NetApp AFF and ASA
* ONTAP Select
* NetApp Cloud Volumes ONTAP

Some hardware options offer better performance, others offer lower costs, and some run within hyperscale clouds. The core functions of ONTAP are unchanged, with multiple replication options available to bind different ONTAP systems into a single solution. As a result, data protection and disaster recovery strategies can be built on real-world needs, such as performance requirements, capital expenditure (capex), or operational expenditure (opex) considerations, and overall cloud strategy. The underlying storage technology runs anywhere in any environment.

ONTAP with AFF and ASA Controllers

For maximum performance and control of data, ONTAP on a physical AFF and ASA systems remains the leading solution. ONTAP delivers solutions for any environment, ranging from single mission-critical databases to 60,000-database service provider deployments, instant restores of petabyte-scale databases, and database as a service (DBaaS) environments involving hundreds of clones of a single database.
