---
sidebar: sidebar
permalink: mysql/lifs.html
keywords: mysql,mariadb,percona,database
summary: MySQL on ONTAP
---

= LIFs

From a functional perspective, LIFs can be divided into the following groups:

* Cluster and node management LIFs. LIFs used to manage the storage cluster.
* SVM management LIFs. Interfaces that permit access to an SVM through the ONTAP API (known as NetApp Manageability SDK) for functions such as Snapshot copy creation or volume resizing. Products such as NetApp SnapCenter must have access to an SVM management LIF.
* Data LIFs. Interfaces that carry FC, iSCSI, NFS, or CIFS data.
* *Note:* A data LIF used for NFS traffic can also be used for management. To do so, change the firewall policy from data to management or another policy that allows HTTP, HTTPS, or SSH. This change can simplify network configuration by avoiding the configuration of each host for access to both the NFS data LIF and a separate management LIF. You cannot configure an interface for both iSCSI and management traffic, even though both use an IP protocol. A separate management LIF is required in iSCSI environments.

For detailed information about LIF types, see the ONTAP Network Management Guide. 

Consider the following primary topics when building a LIF strategy:

* Performance. Is the network bandwidth sufficient?
* Resiliency. Are there any single points of failure in the design?
* Manageability. Can the network be scaled nondisruptively?

These topics apply to the end-to-end solution, from the host through the switches to the storage system.
