---
sidebar: sidebar
permalink: mysql/lun-resizing.html
keywords: mysql,mariadb,percona,database
summary: MySQL on ONTAP
---

= LUN Resizing and LVM-Based Resizing

When a SAN-based file system has reached its capacity limit, there are two options for increasing the space available:

* Increase the size of the LUNs. 
* Add a LUN to an existing volume group and expand the contained logical volumes.

Both options are supportable, but increasing a LUN size is usually more difficult and can be risky. Here are some of the considerations:

* NetApp recommends that you shut down the database before attempting to resize a LUN, and to create Snapshot copies as a fallback measure. Although this recommendation is not a requirement, there is some risk of disruption and user error when rediscovering the newly enlarged LUNs at the host OS level. 

Although LUN resizing is an option to increase capacity, it is usually better to use a logical volume manager (LVM). One of the principal reasons LVMs exist is to avoid the need for a LUN resize. With an LVM, multiple LUNs are bonded together into a virtual pool of storage. The logical volumes carved out of this pool are managed by the LVM and can be resized easily. An LVM also avoids hotspots on a particular LUN by distributing a given logical volume across all available LUNs. You can usually perform transparent migration by using the volume manager to relocate the underlying extents of a logical volume to new LUNs.

For these reasons, NetApp discourages a strategy involving resizing LUNs and encourages an LVM approach.
