---
sidebar: sidebar
permalink: mysql/lun.count.html
keywords: MySQL,MariaDB,TR-4722
summary: MySQL on ONTAP
---


[.lead]

Placeholder



= LUN Count

Unlike the LUN size, the LUN count does affect performance. Database performance is affected by the capability to perform parallel I/O through the SCSI layer. As a result, two LUNs offer better performance than a single LUN. Using a logical volume manager, such as Veritas Volume Manager (VxVM) or Linux LVM2, is the simplest method to increase parallelism. 

NetApp customers have experienced minimal benefit from increasing the number of LUNs beyond eight, although testing of 100% SSD environments with very heavy random I/O has demonstrated further improvement up to 64 LUNs. NetApp recommends building a volume group with an extent size that enables the even distribution of I/O. For example, a 1TB volume group composed of 10 100GB LUNs and an extent size of 100MB would yield 10,000 extents in total (1,000 extents per LUN). The resulting I/O on a database placed on this 1TB volume group should be evenly distributed across all 10 LUNs.

LVM Striping refers to distributing data across multiple LUNs. Before the era of flash drives, striping was used to help overcome the performance limitations of spinning drives. For example, if an OS needs to perform a 1MB read operation, reading that 1MB of data from a single drive would require a lot of drive head seeking and reading as the 1MB is slowly transferred. If that 1MB of data was striped across 8 LUNs, the OS could issue eight 128K read operations in parallel and reduce the time required to complete the 1MB transfer.

Striping with spinning drives was more difficult because the IO pattern had to be known in advance. If the striping wasn多t correctly tuned for the true IO patterns, striped configurations could damage performance. With Oracle databases, and especially with all-flash configurations, striping is much easier to configure and has been proven to dramatically improve performance. 

Some logical volume managers stripe by default, but most do not. Some of them will bond multiple LUNs together as a concatenated device, which results in datafiles that exist on one and only one LUN device. This causes hot spots. Other LVM implementations default to distributed extents. This is similar to striping, but it多s coarser. The LUNs in the volume group are sliced into large pieces, called extents and typically measured in many megabytes, and the logical volumes used by the database are then distributed across those extents. The result is random IO against a datafile should be well distributed across LUNs, but sequential IO operations will not be as efficient as they could be.

Performance-intensive Oracle IO is nearly always either (a) in units of the Oracle block size or (b) one megabyte. Redo logging IO varies in size, but the volume is much lower than database IO and rarely benefits from striping. 

The primary goal of a striped configuration is to ensure that single-file IO多s can be performed as a single unit, and multiblock IO多s, which should be 1MB in size, can be parallelized evenly across all LUNs in the striped volume. This means that the stripe size must not be smaller than the database block size, and the stripe size multiplied by the number of LUNs should be 1MB.

graphic

NetApp recommends the following: 

* In general, four to eight LUNs are sufficient to support data file I/O. Fewer than four LUNs might limit performance because of limitations in host SCSI implementations.
* Configure stripe sizes as 1MB divided by the number of LUNs
