---
sidebar: sidebar
permalink: mysql/mysql-intro.html
keywords: MySQL,MariaDB,TR-4722
summary: MySQL on ONTAP
---


[.lead]

Placeholder



= MySQL

MySQL and its variants, including MariaDb and Percona MySQL, is the world’s most popular database because it has native-rich features. Some of the features are as follows:

* Lower TCO. MySQL is a powerful, free, open-source database management system that has been available for years. It is very stable. It has community support that helps maintain, debug, and add new features. If a web application requires more than a database, or requires load-balancing or sharding, you can easily set up database instances with only hardware costs, rather than commercial databases that require a single license for each instance.
* Reliability, performance, and ease of use. One of MySQL’s hallmarks is exceptional performance and scalability, which is why so many web-based businesses use it. MySQL uses several key strengths to deliver fast performance. Because competition is always a mouse click (or screen touch) away, rapid responses to customer inquiries and activities are paramount. The database serving web-based applications needs to provide extreme performance for both read (simple and complex queries) and write operations. 
* Database development, design, and administration. MySQL Workbench provides an integrated development, design, and administration environment to make developers and DBAs more productive. Different developers look for different features in a database, and MySQL offers a range of features. It can run adequately on both a laptop and a desktop. It can easily adapt to the environment, ensuring that it does not collide with existing web servers or applications.
* Comprehensive transactional support. MySQL is one of the most robust transactional database engines available. It is the solution for full data integrity, offering features such as complete atomic, consistent, isolated, durable transaction support; multiversion transaction support; and unrestricted row-level locking. It provides instant deadlock identification through server-enforced referential integrity.
* Data security. MySQL is globally renowned for being the most secure and reliable database management system used in popular web applications such as WordPress, Drupal, Joomla, Facebook, Google, and Twitter. The data security and support for transactional processing that accompany the recent version of MySQL can benefit any business, especially e-commerce businesses that involve frequent money transfers.
* Pluggable architecture. The MySQL pluggable storage engine architecture enables a database professional to select a specialized storage engine for a particular application need without having to manage application coding requirements. The MySQL server architecture isolates the application programmer and DBA from all the low-level implementation details at the storage level, providing a consistent and easy application model and API. Although there are different capabilities across different storage engines, the application is shielded from these differences.

MySQL's efficient and modular architecture provides huge benefits if you want to target a particular application need—such as data warehousing, transaction processing, or HA situations—while using interfaces and services that are independent of any one storage engine.  

Before designing your storage solution for deploying MySQL on NetApp ONTAP, you should understand the MySQL architecture. The pluggable architecture divides work between MySQL common code (parser, optimizer) and the storage engine. The default storage engine for MySQL, InnoDB, is ACID compatible and is used mostly for OLTP workloads. Its features include:

* ACID transactions
* Row-level locking
* Foreign key constraints
* Automatic crash recovery
* Table compression (read/write)
* Spatial data types (no spatial indexes)
