---
sidebar: sidebar
permalink: mysql/mysql-overview.html
keywords: MySQL,MariaDB,TR-4722
summary: MySQL on ONTAP
---
= MySQL databases on ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
MySQL and its variants, including MariaDb and Percona MySQL, is the world's most popular database.

[NOTE]
This documentation on ONTAP and the MySQL database replaces the previously published _TR-4722: MySQL database on NetApp ONTAP best practices._

ONTAP is an ideal platform for MySQL database because ONTAP is literally designed for databases. Numerous features such as random IO latency optimizations to advanced quality of service (QoS) to basic FlexClone functionality were created specifically to address the needs of database workloads.

Additional features such as nondisruptive upgrades, (including storage replacement) ensure that your critical databases remain available. You can also have instant disaster recovery for large environments through MetroCluster, or select databases using SnapMirror active sync. 

Most importantly, ONTAP delivers unmatched performance with the ability to size the solution for your unique needs. Our high-end systems can deliver over 1M IOPS with latencies measured in microseconds, but if you only need 100K IOPS you can right-size your storage solution with a smaller controller that still runs the exact same storage operating system. 