---
sidebar: sidebar
permalink: mysql/thin-provisioning.html
keywords: MySQL,MariaDB,TR-4722
summary: MySQL on ONTAP
---


[.lead]

Placeholder



= Thin Provisioning

Efficiency features are forms of thin provisioning. For example, a 100GB LUN occupying a 100GB volume might compress down to 50GB. There are no actual savings realized yet, because the volume is still 100GB. The volume must first be reduced in size, so the space saved can be used elsewhere on the system. If later changes to the 100GB LUN result in the data becoming less compressible, the LUN grows and the volume could fill up. 

NetApp strongly recommends thin provisioning, because it can simplify management while delivering a substantial improvement in usable capacity with associated cost savings. The reason is simple: Database environments frequently include a lot of empty space, a large number of volumes and LUNs, and compressible data. Thick provisioning results in reserving space on storage for volumes and LUNs in case they someday become full and contain 100% uncompressible data. This scenario is unlikely. Thin provisioning allows that space to be reclaimed and used elsewhere and allows capacity management to be based on the storage system itself rather than many smaller volumes and LUNs.

Some customers prefer to use thick provisioning, either for specific workloads or according to established operational practices. 

* *Caution:* If a volume is thick provisioned, take care to completely disable all efficiency features for that volume, including decompression and removal of deduplication, by using the sis undo command. The volume should not appear in volume efficiency show output. If it does, the volume is still partially configured for efficiency features. The result is overwriting, which increases the chance that configuration oversights cause the volume to unexpectedly run out of space, resulting in database I/O errors.
