---
sidebar: sidebar
permalink: mysql/virtualized-storage-presentation.html
keywords: MySQL,MariaDB,Percona,database
summary: MySQL on ONTAP
---

= Storage Presentation

Customers considering virtualization of their databases should base their storage decisions on their business needs. Although this statement applies to all IT decisions, it is especially important for virtualization, because the size and scope of projects vary considerably.

Regarding storage presentation, a storage resource should be managed directly by the VM guest. Therefore, use one of the following storage configurations:

* iSCSI LUNs managed by the iSCSI initiator on the VM, not the hypervisor
* NFS file systems mounted by the VM, not a Virtual Machine Disk (VMDK)
* FC raw device mappings (RDMs) when the VM guest manages the file system

As a general rule, avoid using datastores for database files. There are many reasons for this recommendation:

* Transparency. When a VM owns its file systems, it is easier for a database administrator (DBA) or a system administrator to identify the source of the file systems for their data.
* Performance. Testing has shown that channeling all I/O through a hypervisor datastore affects performance.
* Manageability. When a VM owns its file systems, the use or nonuse of a hypervisor layer affects manageability. The same procedures for provisioning, monitoring, data protection, and so on can be used across the entire estate, including virtualized and nonvirtualized environments.
* Stability and troubleshooting. When a VM owns its file systems, delivering good, stable performance and troubleshooting problems are much simpler because the entire storage stack is present on the VM. The hypervisor’s only role is to transport FC or IP frames. When a datastore is included in a configuration, it complicates the configuration by introducing another set of timeouts, parameters, log files, and potential bugs.
* Portability. When a VM owns its file systems, the process of moving a database environment becomes much simpler. File systems can be easily moved between virtualized and nonvirtualized guests.
* Vendor lock-in. After data is placed in a datastore, using a different hypervisor or removing the data from the virtualized environment entirely becomes very difficult.
* Snapshot enablement. In some cases, backups in a virtualized environment can become a problem because of the relatively limited bandwidth. For example, a four-port 10GbE trunk might be sufficient to support day-to-day performance needs of many virtualized databases. However, such a trunk would be insufficient to perform backups using Oracle Recovery Manager (RMAN) or other backup products that require streaming a full-sized copy of the data. 

Using VM-owned file systems makes it easier to take advantage of Snapshot-based backups and restores. A VM-owned file system offloads the work of performing backups onto the storage system. There is no need to overbuild the hypervisor configuration purely to support the bandwidth and CPU requirements in the backup window.

* *Note:* For optimum performance and manageability, NetApp recommends that you avoid placing database data on a datastore. Use guest-owned file systems such as NFS, or use iSCSI file systems managed by the guest or by RDMs. 
