---
sidebar: sidebar
permalink: common/tiering/tiering-policies.html
keywords: tiering, fabricpool
summary: FabricPool Data Tiering Policies
---

= Tiering policies
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
A NetApp FlexVol volume is the basic unit of management for ONTAP. A FlexVol volume does not consume space by itself; rather, it is just a container for files and/or LUNs. Policies, including FabricPool tiering policies, are then set on the volumes as desired.

Four policies are available in ONTAP which control how a block on the performance tier become a candidate to be relocated to the capacity tier.

=== Snapshot-only

The `snapshot-only` `tiering-policy` applies only to blocks that are not shared with the active filesystem. It essentially results in tiering of database backups. Blocks become candidates for tiering after a snapshot is created and the block is then overwritten, resulting in a block that exists only within the snapshot. The delay before a `snapshot-only` block is considered cool is controlled by the `tiering-minimum-cooling-days` setting for the volume. The range as of ONTAP 9.8 is from 2 to 183 days.

Most databases have low change rates, resulting in minimal savings from this policy. For example, a typical database observed on ONTAP has a change rate of less than 5% per week. Exceptions exist, but the rates are usually low. Database archive logs can occupy extensive space, but they usually continue to exist in the active filesystem and thus would not be candidates for tiering under this policy.

=== Auto

The `auto` tiering policy extends tiering to both snapshot-specific blocks as well as blocks within the active filesystem. The delay before a block is considered cool is controlled by the `tiering-minimum-cooling-days` setting for the volume. The range as of ONTAP 9.8 is from 2 to 183 days.

This approach enables tiering options that are not available with the `snapshot-only` policy. For example, a data protection policy might require 90 days of archived log files to be retained. Setting a cooling period of 3 days results in any log files older than 3 days to be tiered out from the performance layer. This action frees up substantial space on the high-speed storage platform while still allowing you to view and manage the full 90 days of data. For a more details, see section link:logs.html[Archive Logs].

=== None

The None policy prevents any additional blocks from being tiered from the storage layer, but any data still in the capacity tier remains in the capacity tier until it is read. If the block is then read, it is pulled back and placed on the performance tier.

The primary reason to use the None policy is to prevent blocks from being tiered, but it could become useful to change the policies over time. For example, let’s say that a specific database is extensively tiered to the capacity layer, but an unexpected need for full performance capabilities arises. The policy can be changed to prevent any additional tiering and to confirm that any blocks read back as the database becomes more active remain in the performance tier.

=== All

The `all` policy replaces the `backup` policy as of ONTAP 9.6. The `backup` policy applied only to data protection volumes, meaning a SnapMirror or NetApp SnapVault destination. The `all` policy functions the same, but is not restricted to data protection volumes.

With this policy, blocks are immediately considered cool and eligible to be tiered to the capacity layer immediately.

This policy is especially appropriate for long-term backups. It can also be used as a form of Hierarchy Storage Management (HSM). In the past, HSM was commonly used to tier the data blocks of a file to tape while keeping the file itself visible on the filesystem. A FabricPool volume with the `all` policy allows you to store files in a visible and manageable yet consuming nearly no space on the local storage tier.
