---
sidebar: sidebar
permalink: postgres/appendix-a.html
keywords: PostgreSQL,database,postgres
summary: PostgreSQL Databases on ONTAP
---
= Appendix A: Host configuration
:icons: font
:imagesdir: ../media/

[.lead]
Appendix content:

* Verify that FC host bus adapters (HBAs) in the ESX host are running with updated drivers, firmware, and the correct BIOS version.

* Install NetApp Host Utilities on the host to view direct and indirect paths for a given LUN. The kit also provides extended information about the LUN SVM information. 

* Always use a rescan SCSI bus script on the host to:

* Find new LUNs

* Discard stale LUNs

* Update new paths to LUNs

* To establish multiple routes to the storage if there is path failure, install and configure multipathing software on the host operating system. 

* If you are not using multipathing software, you should limit each LUN to a single path.

* The Linux kernel allows low-level control over the scheduling of I/O to block devices. The defaults in Linux versions might vary considerably. In general, NetApp customers and internal testing show better results with NoOps scheduler for databases. You should perform benchmarking to determine which I/O schedulers are optimal for your use case.
