---
sidebar: sidebar
permalink: postgres/overview.html
keywords: PostgreSQL,database,postgres
summary: PostgreSQL Databases on ONTAP
---
= PostgreSQL databases on ONTAP

[.lead]
PostgreSQL comes with variants that include PostgreSQL, PostgreSQL Plus, and EDB Postgres Advanced Server (EPAS). PostgreSQL is typically deployed as the back-end database for multitier applications. It is supported by common middleware packages (such as PHP, Java, Python, Tcl/Tk, ODBC, and JDBC) and has historically been a popular choice for open-source database management systems. NetApp ONTAP is a excellent choice for running PostgreSQL databases do to its reliability, high performing and efficent data management capabilities.

[NOTE]
_This documentation on ONTAP and the PostgreSQL database replaces the previously published TR-4770: PostgreSQL database on ONTAP best practices._

As data grows exponentially, data management becomes more complex for enterprises. This complexity increases licensing, operational, support, and maintenance costs. To reduce the overall TCO, consider switching from commercial to open-source databases with reliable, high-performing back-end storage. PostgreSQL is an advanced open-source database that is widely used in academic, commercial, and large enterprises. It comes with a new set of features that addresses the gaps in other relational database management systems (RDBMSs).

[NOTE]
NetApp customers who use PostgreSQL databases in either physical or virtualized environments can benefit from understanding the best practices for successfully deploying and managing PostgreSQL databases on ONTAP. The recommendations are generic, so they are not specific to any configuration. Depending on your business needs, some suggestions might require changes. You must evaluate your environment against the official documentation for PostgreSQL, hypervisors, OS, and ONTAP storage.