---
sidebar: sidebar
permalink: postgres/security.html
keywords: PostgreSQL,database,postgres
summary: PostgreSQL Databases on ONTAP
---


[.lead]

Placeholder



= Database security

As cases of ransomware threats have increased considerably, securing user and business data is very critical to your organization. While administrators set appropriate permissions, you can set the firewall policy to grant selective access of the database to users. Attackers might still find ways to hijack data.  ONTAP offers a variety of capabilities to secure data on NAS and SAN.

Tamperproof snapshots: We mentioned previously about using snapshots for a quick database backup. An attacker might delete snapshots which could have been the last option to restore a database in case of data corruption. Enabling tamperproof snapshots locks the snapshot for a specified period making sure the copy cannot be deleted accidentally or maliciously. The tamperproof snapshot feature is available from ONTAP 9.12.1 and requires the SnapLock license and compliance clock to be turned on.

ONTAP has a multi-admin verification (MAV) feature which means no single administrator has a complete privilege to delete snapshots or modify volumes. This can act as additional security to avoid volumes or snapshots getting tampered with by rogue administrators.
