---
sidebar: sidebar
permalink: postgres/snapshot-dp.html
keywords: PostgreSQL,database,postgres
summary: PostgreSQL Databases on ONTAP
---


[.lead]

Placeholder



= Snapshot technology

NetApp has developed a full portfolio of technologies and tools to help organizations build or adapt their backup and recovery plans to respond to all business demands. With the NetApp Snapshot technology that is included in ONTAP software, you can create backups or execute restore operations for datasets of any size in a matter of seconds. For PostgreSQL, you must enable Snapshots for data files, WAL files, and archived WAL files to provide full or point-in-time recovery.

For PostgreSQL databases, the average backup time with Snapshot copies is in the range of a few seconds to a few minutes. This backup speed is 60 to 100 times faster than pg_basebackup and other file-system-based backup approaches.

Snapshot copies on NetApp storage can be both crash-consistent and application-consistent. A crash-consistent snapshot is created on storage without quiescing the database, whereas an application-consistent snapshot is created while the database is in backup mode. NetApp also ensures that subsequent Snapshot copies are incremental-forever backups to promote storage savings and network efficiency.

Because Snapshot copies are rapid and do not affect system performance, you can schedule multiple Snapshot copies daily instead of creating a single daily backup as with other streaming backup technology. When a restore and recovery operation is necessary, the system downtime is reduced by two key features:

* NetApp SnapRestore data recovery technology means that the restore operation is executed in seconds.
* Aggressive recovery point objectives (RPOs) mean that fewer database logs must be applied and forward recovery is also accelerated.

For backing up PostgreSQL, you must ensure that the data volumes are copied simultaneously with (consistency-group) WAL and the archived logs. While you are using Snapshot technology to copy WAL files, make sure that you run pg_stop to flush all the WAL entries that must be archived. If you flush the WAL entries during the restore, then you only need to stop the database, unmount, or delete the existing data directory and perform a SnapRestore operation on storage. After the restore is done, you can mount the system and bring it back to its current state. For point-in-time recovery, you can also restore WAL and archive logs; then PostgreSQL decides the most consistent point and recovers it automatically.

Consistency groups are a feature in ONTAP and are recommended when there are multiple volumes mounted to a single instance or a database with multiple tablespaces. A consistency group snapshot ensures all volumes are grouped together and protected. A consistency group can be managed efficiently from ONTAP System Manager and you can even clone it to create an instance copy of a database for testing or development purposes.
