---
sidebar: sidebar
permalink: postgres/summary.html
keywords: PostgreSQL,database,postgres
summary: PostgreSQL Databases on ONTAP
---


[.lead]

Placeholder



= Best practices summary

The following are the best practices and recommendations for deploying PostgreSQL on ONTAP data management software. 

Best Practices
* In a multitenant PostgreSQL environment, each tenant's data (database or instance) can have a dedicated SVM on ONTAP storage.

* Enabling LACP and IP load balancing is the most common approach during NFS LIF design. Otherwise, failover policies and groups should be configured in the regular method.
* For a SAN multipathing environment, it is better to have a NetApp LUN host zoned from different switches to ensure high availability.
* Any FC zone should never contain more than one initiator. Crosstalk between initiators eventually interferes with performance and stability.
* During LUN or volume moves in a HA cluster, the LUN must be presented using the destination storage controllers before the mobility event is initiated. Modify the selective LUN map reporting-nodes list before moving.
* In a mission critical environment, NetApp recommends keeping data files and WAL logs on dedicated volumes or LUNs for better performance. This applies to both the SAN and NFS layouts.
* Isolation of data files and WAL logs in a dedicated volume also enables faster recovery of the database.
* For better database performance, isolate the critical tablespaces on a dedicated volume or LUN.
* Choosing datastores might improve the overall manageability and operational overhead.
* Datastores might add extra layer of complexity by having another set of timeouts, parameters, log files, and potential bugs.
* Choosing NFS over VMFS datastore helps when using the NetApp SnapRestore technology in a disaster scenario
* An index that is heavily used can be placed on a fast, highly available disk, such as an expensive solid-state device. Also, a table storing archived data that is rarely used or not performance critical can be stored on a less expensive, slower disk system.
* Tablespaces depend on metadata in the main data directory, and therefore cannot be attached to a different database cluster or backed up individually. Similarly, if you lose a tablespace (through file deletion, disk failure, and so on), the database cluster might become unreadable or unable to start. Placing a tablespace on a temporary file system like a RAM disk risks the reliability of the entire cluster.
* NetApp does not recommend making more than one tablespace per logical file system, because you cannot control the location of individual files in a logical file system.
* NetApp recommends using version 4 of the NFS protocol, because it has an integrated locking feature that version 3 lacks. Also, it has new features such as statefulness, improved security, and strong authentication.
* PostgreSQL does not recommend soft mounting of an NFS file system.
* PostgreSQL also advises mounting the NFS file system synchronously to avoid a data inconsistency problem. For more information, see the PostgreSQL documentation.
* Ensure that the database has multiple tablespaces, with tables and indexes grouped according to the transaction rates.
* The tablespace must be placed across multiple disk file systems for balanced I/O. This balance ensures that multiple CPUs come into play to perform transactions across multiple disks. 
